const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const INTERNAL_SERVICE_ERROR = 500;
const CONFLICT = 409;

module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  INTERNAL_SERVICE_ERROR,
  CONFLICT,
  UNAUTHORIZED,
  FORBIDDEN,
};
